# Generated by Django 6.0.2 on 2026-03-03 18:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_default", models.BooleanField(default=False)),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_won", models.BooleanField(default=False)),
                ("is_lost", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="organizations.organization",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="crm_pipelines.pipeline",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(
                fields=["organization", "ordering"], name="idx_pipeline_org_ordering"
            ),
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(
                fields=["organization", "is_default"], name="idx_pipeline_org_default"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uq_pipeline_org_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("organization",),
                name="uq_pipeline_one_default_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(
                fields=["organization", "pipeline", "order"],
                name="idx_stage_org_pipeline_order",
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["organization", "pipeline"], name="idx_stage_org_pipeline"),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("organization", "pipeline", "name"),
                name="uq_stage_org_pipeline_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("organization", "pipeline", "order"),
                name="uq_stage_org_pipeline_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_won", True), ("is_lost", True), _negated=True),
                name="ck_stage_not_won_and_lost",
            ),
        ),
    ]
