# Generated by Django 5.2.12 on 2026-05-16 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='conversion_probability',
            field=models.PositiveSmallIntegerField(default=0, help_text='Probabilidade estimada de conversão desta etapa no funil, de 0 a 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
